---
title: "Homework 3"
author: "Austin Chan"
date: "3/24/2020"
output: html_document
---

```{r}
library(MASS)
library(caret)
library(ggplot2)
library(dplyr)
library(corrplot)
library(reshape2)
library(tidyr)
library(pROC)
library(gridExtra)
library(pander)
```



```{r}
raw = read.csv(".//crime-training-data_modified.csv", stringsAsFactors = F)

scaled_data = data.frame(scale(raw[,!names(raw) %in% c("target","chas")]))

scaled_data$chas = raw$chas
scaled_data$target = as.factor(raw$target)
```



```{r}
hist(scaled_data$zn)

hist(scaled_data$indus)

hist(scaled_data$chas)

hist(scaled_data$nox)

hist(scaled_data$rm)

hist(scaled_data$age)

hist(scaled_data$dis)

hist(scaled_data$rad)

hist(scaled_data$tax)

hist(scaled_data$ptratio)

hist(scaled_data$lstat)

hist(scaled_data$medv)
```

```{r}
dim(scaled_data)

#summary stats
sum_data <- summary(scaled_data)
pander(sum_data, split.table = 100, style = 'rmarkdown')

#missing values
scaled_data %>%
  summarise_all(list(~sum(is.na(.))))
```
```{r}
density_data <- melt(scaled_data[c(1:13)])

#density plots
ggplot(density_data, aes(value)) + geom_density(fill = "blue") + facet_wrap(~variable, scales = "free")
```
```{r}
#box plots
plot1 <- ggplot(scaled_data, aes(x = target, y = indus, group=target)) + geom_boxplot() + coord_flip()
plot2 <- ggplot(scaled_data, aes(x = target, y = nox, group=target)) + geom_boxplot() + coord_flip()
plot3 <- ggplot(scaled_data, aes(x = target, y = age, group=target)) + geom_boxplot() + coord_flip()
plot4 <- ggplot(scaled_data, aes(x = target, y = dis, group=target)) + geom_boxplot() + coord_flip()
plot5 <- ggplot(scaled_data, aes(x = target, y = rad, group=target)) + geom_boxplot() + coord_flip()
plot6 <- ggplot(scaled_data, aes(x = target, y = tax, group=target)) + geom_boxplot() + coord_flip()
plot7 <- ggplot(scaled_data, aes(x = target, y = zn, group=target)) + geom_boxplot() + coord_flip()
plot8 <- ggplot(scaled_data, aes(x = target, y = rm, group=target)) + geom_boxplot() + coord_flip()
plot9 <- ggplot(scaled_data, aes(x = target, y = ptratio, group=target)) + geom_boxplot() + coord_flip()
plot10 <- ggplot(scaled_data, aes(x = target, y = lstat, group=target)) + geom_boxplot() + coord_flip()
plot11 <- ggplot(scaled_data, aes(x = target, y = medv, group=target)) + geom_boxplot() + coord_flip()
plot12 <- ggplot(scaled_data, aes(x = target, y = chas, group=target)) + geom_boxplot() + coord_flip()

grid.arrange(plot1,plot2,plot3,plot4,plot5,plot6,plot7,plot8,plot9,plot10,plot11,plot12, ncol=3)
```

```{r}
#correlation matrix
data_cor = cor(raw)
corrplot(data_cor, type = "lower")
```

```{r}
set.seed(100)

scaled_index = createDataPartition(scaled_data$target, p = 0.8, list = F)

scaled_train = scaled_data[scaled_index,]
scaled_test = scaled_data[-scaled_index,]
```


```{r}
base_model = glm(target~.,data = scaled_train, family = binomial)

summary(base_model)
```

```{r}
stepAIC_model = stepAIC(base_model, direction = "both")

summary(stepAIC_model)
```


```{r}
caret_model = train(
  form = target~.,
  data = scaled_train,
  trControl = trainControl(method = "cv", number = 5),
  method = "glm",
  family = "binomial"
)
```

```{r}
caret_model
```

```{r}
summary(stepAIC_model)

summary(caret_model)
```

```{r}
caret_results = predict(caret_model, newdata = scaled_test, type = "prob")

step_aic_results = predict.glm(stepAIC_model, newdata = scaled_test, type = "response")
```

```{r}
caret_results$predictions = 0
caret_results$predictions[caret_results$`1` >= 0.5] = 1
caret_results$predictions = as.factor(caret_results$predictions)

caret_results

step_aic_results_df = data.frame(probs = step_aic_results)
step_aic_results_df$predictions = 0
step_aic_results_df$predictions[step_aic_results_df$probs >= 0.5] = 1
step_aic_results_df$predictions = as.factor(step_aic_results_df$predictions)

step_aic_results_df
```

```{r}
caret::confusionMatrix(caret_results$predictions,scaled_test$target, positive = "1")
```

```{r}
caret::confusionMatrix(step_aic_results_df$predictions,scaled_test$target, positive = "1")
```

```{r}
#Log transformation on skewed predictors
transformation <- training_data %>% mutate_at(c("nox", "dis", "age", "zn", "lstat", "medv", "chas", "ptratio"), log)

#potential models
model_5 <- glm(target ~ indus + nox + age + dis + rad + tax, family = binomial(link = "logit"), data = transformation)
summary(model_5) #AIC: 232.91 0.6610585

model_6 <- glm(target ~ nox + dis + rad + tax, family = binomial(link = "logit"), data = transformation)
summary(model_6) #AIC: 230.14 0.6591609

#residual plots
par(mfrow = c(2, 2))
plot(model_2)

hist(model_2$residuals)
qqnorm(model_2$residuals)
qqline(model_2$residuals)

#test model
trainingMinus <- transformation %>% select(-target)

test_results <- predict(model_6, newdata = transformation, type = "response")

df <- bind_cols(transformation, data.frame(scored_target = test_results)) %>% 
    mutate(scored_target = if_else(scored_target > 0.5, 1, 0)) #%>% print

#Performance
cm <- confusionMatrix(as.factor(df$scored_target), as.factor(df$target), positive = "1", 
    mode = "everything") %>% print #Accuracy : 0.8584 AUC:0.84

curveRoc <- roc(df$target, df$scored_target)
curveRoc$auc

#plot(curveRoc, legacy.axes = T, main = "pROC")

plot(curveRoc[[1]], 
     main = "ROC Curve",
     xlab = "False Postive Rate",
     ylab = "True Positive Rate")
```









